# Generated by Django 5.0.2 on 2024-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hsn', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=100)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_of_invoice', models.DateField()),
                ('uqc', models.CharField(max_length=50)),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_invoice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=50)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('gstr2b', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ledger', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tblPartNumber',
            },
        ),
        migrations.CreateModel(
            name='tblProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_code', models.CharField(max_length=100)),
                ('project_name1', models.CharField(max_length=255)),
                ('project_code1', models.CharField(max_length=100)),
                ('projcode_partnumber', models.CharField(max_length=100)),
                ('projcode_partname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblProject',
            },
        ),
        migrations.CreateModel(
            name='tblVendordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_code', models.CharField(max_length=100, unique=True)),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'tblVendordetails',
            },
        ),
    ]
