# Generated by Django 5.0.2 on 2024-12-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=100)),
                ('Project_name', models.CharField(max_length=255)),
                ('Custmer_id', models.CharField(max_length=255)),
                ('Custmer_name', models.CharField(max_length=255)),
                ('InvoiceValues', models.TextField(blank=True, max_length=255)),
                ('PartNums', models.TextField(blank=True, max_length=255)),
                ('PartNames', models.TextField(blank=True, max_length=255)),
                ('Qty', models.CharField(blank=True, max_length=255)),
                ('TotalValue', models.CharField(blank=True, max_length=255)),
                ('HSN', models.CharField(blank=True, max_length=255)),
                ('GSTRate', models.CharField(max_length=255)),
                ('CostPerunit', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'tbl_costing',
            },
        ),
        migrations.CreateModel(
            name='CreateCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTID', models.CharField(max_length=100)),
                ('CustomerName', models.CharField(max_length=255)),
                ('CustomerGSTIN', models.CharField(max_length=15, unique=True)),
                ('CustomerADdress', models.TextField()),
                ('CustomerPAN', models.CharField(max_length=255)),
                ('TypeofCustomer', models.CharField(max_length=100)),
                ('BankAcc', models.CharField(max_length=100)),
                ('IFSC', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_CreateCustomer',
            },
        ),
        migrations.CreateModel(
            name='CreateInvoiceBasedPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('VENDID', models.CharField(max_length=255)),
                ('VendorInvoiceNumber', models.CharField(max_length=255)),
                ('YearOfInvoice', models.CharField(max_length=255)),
                ('InvoicePartNumber', models.CharField(max_length=255)),
                ('BAtchID', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_CreateInvoiceBasedPartNumber',
            },
        ),
        migrations.CreateModel(
            name='CreateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=100)),
                ('CUSTID', models.CharField(max_length=255)),
                ('CustomerName', models.CharField(max_length=255)),
                ('ProjectNAme', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('ProjCodePArtNumberSuffix', models.CharField(max_length=255)),
                ('ProjCodePartNameSuffix', models.CharField(max_length=255)),
                ('FY', models.TextField()),
            ],
            options={
                'db_table': 'tbl_CreateProject',
            },
        ),
        migrations.CreateModel(
            name='CreatePurchaseBasedCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255, unique=True)),
                ('COSTID', models.CharField(max_length=255)),
                ('InvoiceValues', models.TextField(max_length=255)),
                ('PartNums', models.TextField(max_length=255)),
                ('PartNames', models.TextField(max_length=255)),
                ('Qty', models.CharField(max_length=255)),
                ('TotalValue', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_CreatePurchaseBasedCosting',
            },
        ),
        migrations.CreateModel(
            name='CreateVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VENDID', models.CharField(max_length=255, unique=True)),
                ('VendorNAme', models.CharField(max_length=255)),
                ('VEndorGSTIN', models.CharField(max_length=15, unique=True)),
                ('VendorAddress', models.TextField()),
                ('VendorPAN', models.CharField(blank=True, max_length=255)),
                ('TypeofVendor', models.CharField(max_length=100)),
                ('BankAcc', models.CharField(max_length=100)),
                ('IFSC', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_CreateVendor',
            },
        ),
        migrations.CreateModel(
            name='EnggBOMUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCHID', models.CharField(max_length=255)),
                ('PROJID', models.CharField(max_length=255)),
                ('SCHEnggBOMPath', models.CharField(max_length=255)),
                ('SchEnggBOMCreatedOn', models.CharField(max_length=255)),
                ('EnggBOMVersionNumber', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_EnggBOMUpload',
            },
        ),
        migrations.CreateModel(
            name='InternationalCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('cust_id', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('type_of_customer', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('aba_routing_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_InternationalCustomers_1',
            },
        ),
        migrations.CreateModel(
            name='InternationalCustomers2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('cust_id', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('type_of_customer', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('aba_routing_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_InternationalCustomers_2',
            },
        ),
        migrations.CreateModel(
            name='MechanicalDrawingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MECHID', models.CharField(max_length=255)),
                ('PROJID', models.CharField(max_length=255)),
                ('MechDrawingNAme', models.CharField(max_length=255)),
                ('MechStepFileCreatedOn', models.CharField(max_length=255)),
                ('MechStepFilePath', models.CharField(max_length=255)),
                ('MechCADDrawingCreatedOn', models.CharField(max_length=255)),
                ('MechCADDrawingPAth', models.CharField(max_length=255)),
                ('MechBOMPath', models.CharField(max_length=255)),
                ('MechBOMCreatedOn', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_MechanicalDrawingUpload',
            },
        ),
        migrations.CreateModel(
            name='MechBOMUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MECHID', models.CharField(max_length=255)),
                ('PROJID', models.CharField(max_length=255)),
                ('SlNo', models.CharField(max_length=255)),
                ('QuantityPerUnit', models.CharField(max_length=255)),
                ('PART', models.CharField(max_length=255)),
                ('Part_Description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_MechBOMUpload',
            },
        ),
        migrations.CreateModel(
            name='PCBArtifactUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCHID', models.CharField(max_length=255)),
                ('PROJID', models.CharField(max_length=255)),
                ('PCBID', models.CharField(max_length=255)),
                ('PCBLegendName', models.CharField(max_length=255)),
                ('PCBNAme', models.CharField(max_length=255)),
                ('PCBCreatedOn', models.CharField(max_length=255)),
                ('PCBGerberPath', models.CharField(max_length=255)),
                ('PCBGerberUploadDatetime', models.CharField(max_length=255)),
                ('PCBPanelGerberPath', models.CharField(max_length=255)),
                ('PCBPanelGerberUploadDateTime', models.CharField(max_length=255)),
                ('PCBPhoto', models.ImageField(upload_to='pcb_photos/')),
            ],
            options={
                'db_table': 'tbl_PCBArtifactUpload',
            },
        ),
        migrations.CreateModel(
            name='PCBOrderDetailsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCBID', models.CharField(max_length=255)),
                ('PROJID', models.CharField(max_length=255)),
                ('PCBOrderDateTime', models.CharField(max_length=255)),
                ('PCBOrderQuantity', models.CharField(max_length=255)),
                ('PCBVendorID', models.CharField(max_length=255)),
                ('PCBVendorName', models.CharField(max_length=255)),
                ('PCBReceiptDateTime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_PCBOrderDetailsUpload',
            },
        ),
        migrations.CreateModel(
            name='ReadPurchaseBasedCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('COSTID', models.CharField(max_length=255)),
                ('TotalValue', models.CharField(max_length=255)),
                ('CostDetails', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_ReadPurchaseBasedCosting',
            },
        ),
        migrations.CreateModel(
            name='SchArtifactUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCHID', models.CharField(max_length=255)),
                ('PROJID', models.CharField(max_length=255)),
                ('SchName', models.CharField(max_length=255)),
                ('SCHPDFPath', models.CharField(max_length=255)),
                ('SCHDSNPath', models.CharField(max_length=255)),
                ('SchCreatedOn', models.CharField(max_length=255)),
                ('SchVersion', models.CharField(max_length=255)),
                ('Last_Updated', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_SchArtifactUpload',
            },
        ),
        migrations.CreateModel(
            name='UploadInvoicefromVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('VENDID', models.CharField(max_length=255)),
                ('VendorInvoiceNumber', models.CharField(max_length=255)),
                ('VendorNAme', models.CharField(max_length=255)),
                ('DateofInvoice', models.CharField(max_length=255)),
                ('UnitOfMeasure', models.CharField(max_length=255)),
                ('QtyReceived', models.CharField(max_length=255)),
                ('GSTRate', models.CharField(max_length=255)),
                ('InvoiceValue', models.CharField(max_length=255)),
                ('HSN', models.CharField(max_length=255)),
                ('CostPerunit', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalValue', models.CharField(blank=True, max_length=255, null=True)),
                ('Part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('Part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('CGST', models.CharField(blank=True, max_length=255, null=True)),
                ('SGST', models.CharField(blank=True, max_length=255, null=True)),
                ('IGST', models.CharField(blank=True, max_length=255, null=True)),
                ('OptionType', models.CharField(choices=[('LOCAL', 'LOCAL'), ('INTERSTATE', 'INTERSTATE')], max_length=255)),
            ],
            options={
                'db_table': 'tbl_UploadInvoicefromVendor',
            },
        ),
        migrations.RenameField(
            model_name='tblproject',
            old_name='project_code1',
            new_name='project_code',
        ),
        migrations.RenameField(
            model_name='tblproject',
            old_name='project_name1',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='tblvendordetails',
            name='Pan_details',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblvendordetails',
            name='Tally_ledger_creation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblproject',
            name='company_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tblproject',
            name='projcode_partnumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tblvendordetails',
            name='gstin',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblvendordetails',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='tblvendordetails',
            table=None,
        ),
    ]
