# Generated by Django 5.0.2 on 2024-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_costing_createcustomer_createinvoicebasedpartnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanicaldrawingupload',
            old_name='MechCADDrawingPAth',
            new_name='MechCADDrawingPath',
        ),
        migrations.RenameField(
            model_name='mechanicaldrawingupload',
            old_name='MechDrawingNAme',
            new_name='MechDrawingName',
        ),
        migrations.AlterField(
            model_name='mechanicaldrawingupload',
            name='MechStepFilePath',
            field=models.FileField(upload_to='mechanical_drawings/'),
        ),
    ]
