# Generated by Django 5.0.2 on 2024-12-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_mechcaddrawingpath_mechanicaldrawingupload_mechcaddrawingpath_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR2B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin_supplier', models.CharField(max_length=50, verbose_name='GSTIN of Supplier')),
                ('trade_name', models.CharField(max_length=255, verbose_name='Trade/Legal Name')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_type', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('place_of_supply', models.CharField(max_length=100)),
                ('supply_reverse_charge', models.CharField(max_length=10, verbose_name='Supply Attract Reverse Charge')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('integrated_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('central_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state_ut_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cess', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gstr_period', models.CharField(max_length=20, verbose_name='GSTR-1/IFF/GSTR-5 Period')),
                ('gstr_filing_date', models.DateField(verbose_name='GSTR-1/IFF/GSTR-5 Filing Date')),
                ('itc_availability', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_GSTR2B',
            },
        ),
    ]
