# Generated by Django 5.1.4 on 2024-12-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gstr2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='schartifactupload',
            name='ProjectName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
