# Generated by Django 5.1.4 on 2024-12-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_schartifactupload_projectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicaldrawingupload',
            name='ProjectName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechbomupload',
            name='ProjectName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
