# Generated by Django 5.1.4 on 2024-12-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mechanicalprojecttree'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectId', models.CharField(max_length=255, null=True)),
                ('ProjectName', models.CharField(max_length=255, null=True)),
                ('ParentId', models.CharField(max_length=255)),
                ('ParentName', models.CharField(max_length=255)),
                ('ChildId', models.CharField(max_length=255)),
                ('ChildName', models.CharField(max_length=255)),
                ('Path', models.CharField(max_length=255)),
                ('DrawingName', models.CharField(max_length=255)),
                ('DrawingId', models.CharField(max_length=255)),
                ('DrawingPath', models.CharField(max_length=255)),
                ('Reamrks', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_MechProject',
            },
        ),
    ]
