# Generated by Django 5.1.4 on 2025-01-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pcbproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateVendorStoresInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('VENDID', models.CharField(max_length=255)),
                ('VendorInvoiceNumber', models.CharField(max_length=255)),
                ('VendorDCNumber', models.CharField(max_length=255)),
                ('DescriptionofItem', models.CharField(max_length=255)),
                ('QuantityReceived', models.CharField(max_length=255)),
                ('UnitofMEasure', models.CharField(max_length=255)),
                ('BatchID', models.CharField(max_length=255)),
                ('PurchaseORderNumber', models.CharField(max_length=255)),
                ('AcceptedQuantity', models.CharField(max_length=255)),
                ('RejectedQuantity', models.CharField(max_length=255)),
                ('Remarks', models.CharField(max_length=255)),
                ('Receivedby', models.CharField(max_length=255)),
                ('LocationinStore', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblCreateVendorStoresInward',
            },
        ),
    ]
