# Generated by Django 5.1.4 on 2025-01-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_schproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCustomerStoresInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('CUSTID', models.CharField(max_length=255)),
                ('CustomerDCNumber', models.CharField(max_length=255)),
                ('DescriptionofItem', models.CharField(max_length=255)),
                ('QuantityReceived', models.CharField(max_length=255)),
                ('UnitofMEasure', models.CharField(max_length=255)),
                ('CauseofInward', models.CharField(max_length=255)),
                ('Remarks', models.CharField(max_length=255)),
                ('Receivedby', models.CharField(max_length=255)),
                ('LocationinStore', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblCreateCustomerStoresInward',
            },
        ),
    ]
