# Generated by Django 5.1.4 on 2025-01-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_createothersstoresinward'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStoresOutwardtoProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('BatchID', models.CharField(max_length=255)),
                ('InvoicePartNumber', models.CharField(max_length=255)),
                ('Quantity', models.CharField(max_length=255)),
                ('TotalValue', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblCreateStoresOutwardtoProduction',
            },
        ),
    ]
