# Generated by Django 5.1.3 on 2025-02-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_createstoresoutwardtorepairs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadinvoicefromvendor",
            name="BatchId",
            field=models.CharField(default="0000", max_length=50),
        ),
        migrations.AddField(
            model_name="uploadinvoicefromvendor",
            name="Description",
            field=models.CharField(default="No Description", max_length=255),
        ),
    ]
