# Generated by Django 5.1.4 on 2025-02-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_uploadinvoicefromvendor_batchid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=100)),
                ('bin_name', models.CharField(max_length=255)),
                ('type_of_bin', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_Bins',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.CharField(max_length=100)),
                ('rack_name', models.CharField(max_length=255)),
                ('number_of_shelf', models.CharField(max_length=255)),
                ('number_of_bin_per_shelf', models.CharField(max_length=255)),
                ('rack_location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_Racks',
            },
        ),
        migrations.CreateModel(
            name='RacksandBinsMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.CharField(max_length=255)),
                ('rack_name', models.CharField(max_length=255)),
                ('bin_id', models.CharField(max_length=100)),
                ('bin_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_Racks_and_Bins_Mapping',
            },
        ),
        migrations.AlterField(
            model_name='uploadinvoicefromvendor',
            name='Description',
            field=models.CharField(max_length=255),
        ),
    ]
