# Generated by Django 5.1.4 on 2025-02-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('test_date', models.DateField()),
                ('tested_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConclusionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('next_steps', models.TextField()),
                ('approved_by', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion', to='myapp.hardwaretestreport')),
            ],
        ),
        migrations.CreateModel(
            name='IssueObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('suggested_resolution', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='myapp.hardwaretestreport')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_no', models.IntegerField()),
                ('test_description', models.TextField()),
                ('expected_outcome', models.TextField()),
                ('actual_outcome', models.TextField()),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='myapp.hardwaretestreport')),
            ],
        ),
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_version', models.CharField(max_length=50)),
                ('firmware_version', models.CharField(max_length=50)),
                ('test_equipment_used', models.TextField()),
                ('operating_conditions', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='myapp.hardwaretestreport')),
            ],
        ),
    ]
