# Generated by Django 5.1.4 on 2025-03-05 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('firmware_version', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Firmware_FirmwareAPI',
            },
        ),
        migrations.CreateModel(
            name='ADC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField()),
                ('resolution', models.CharField(max_length=50)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adc', to='myapp.firmwareapi')),
            ],
            options={
                'db_table': 'Firmware_ADC',
            },
        ),
        migrations.CreateModel(
            name='GPIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('mode', models.CharField(max_length=50)),
                ('pull', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpio', to='myapp.firmwareapi')),
            ],
            options={
                'db_table': 'Firmware_GPIO',
            },
        ),
        migrations.CreateModel(
            name='I2C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i2c', to='myapp.firmwareapi')),
            ],
            options={
                'db_table': 'Firmware_I2C',
            },
        ),
        migrations.CreateModel(
            name='SPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('clock_speed', models.IntegerField()),
                ('polarity', models.CharField(max_length=50)),
                ('phase', models.CharField(max_length=50)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi', to='myapp.firmwareapi')),
            ],
            options={
                'db_table': 'Firmware_SPI',
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('period', models.IntegerField()),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='myapp.firmwareapi')),
            ],
            options={
                'db_table': 'tbl_Firmware_Timer',
            },
        ),
        migrations.CreateModel(
            name='UART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baudrate', models.IntegerField()),
                ('parity', models.CharField(max_length=20)),
                ('stop_bits', models.IntegerField()),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uart', to='myapp.firmwareapi')),
            ],
            options={
                'db_table': 'Firmware_UART',
            },
        ),
    ]
