# Generated by Django 5.1.4 on 2025-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_firmwareapi_adc_gpio_i2c_spi_timer_uart'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('firmware_version', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('scope', models.TextField()),
                ('references', models.TextField()),
                ('architecture', models.TextField()),
                ('dependencies', models.TextField()),
                ('gpio_api', models.TextField()),
                ('uart_api', models.TextField()),
                ('timer_api', models.TextField()),
                ('adc_api', models.TextField()),
                ('spi_api', models.TextField()),
                ('i2c_api', models.TextField()),
                ('error_handling', models.TextField()),
                ('usage_examples', models.TextField()),
                ('testing_validation', models.TextField()),
                ('conclusion', models.TextField()),
                ('approver_name', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='spi',
            name='firmware',
        ),
        migrations.RemoveField(
            model_name='uart',
            name='firmware',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='firmware',
        ),
        migrations.RemoveField(
            model_name='i2c',
            name='firmware',
        ),
        migrations.RemoveField(
            model_name='gpio',
            name='firmware',
        ),
        migrations.DeleteModel(
            name='ADC',
        ),
        migrations.DeleteModel(
            name='SPI',
        ),
        migrations.DeleteModel(
            name='UART',
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
        migrations.DeleteModel(
            name='I2C',
        ),
        migrations.DeleteModel(
            name='FirmwareAPI',
        ),
        migrations.DeleteModel(
            name='GPIO',
        ),
    ]
