# Generated by Django 5.1.4 on 2025-03-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_firmwaretestreport_remove_spi_firmware_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='firmwaretestreport',
            table='myapp_Firmware API Document',
        ),
    ]
