# Generated by Django 5.1.4 on 2025-03-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_firmwaretestreport_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='firmwaretestreport',
            table='API_Firmware API Document',
        ),
    ]
