# Generated by Django 5.1.4 on 2025-03-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_firmwaretestreport_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareDriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('firmware_version', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('scope', models.TextField()),
                ('references', models.TextField()),
                ('microcontroller', models.TextField()),
                ('architecture', models.TextField()),
                ('gpio_driver', models.TextField()),
                ('uart_protocol', models.TextField()),
                ('timer_driver', models.TextField()),
                ('adc_driver', models.TextField()),
                ('spi_driver', models.TextField()),
                ('i2c_driver', models.TextField()),
                ('error_handling', models.TextField()),
                ('test_validation', models.TextField()),
                ('conclusion', models.TextField()),
                ('approver_name', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
            ],
            options={
                'db_table': 'API_Firmware Driver Document',
            },
        ),
    ]
