# Generated by Django 5.1.4 on 2025-03-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_firmwaredriverdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareLowLevelDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('firmware_version', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('scope', models.TextField()),
                ('references', models.TextField()),
                ('hardware_overview', models.TextField()),
                ('firmware_structure', models.TextField()),
                ('startup_sequence', models.TextField()),
                ('bootloader', models.TextField()),
                ('gpio_driver', models.TextField()),
                ('uart_driver', models.TextField()),
                ('timer_driver', models.TextField()),
                ('adc_driver', models.TextField()),
                ('other_peripherals', models.TextField()),
                ('task_management', models.TextField()),
                ('error_handling', models.TextField()),
                ('memory_management', models.TextField()),
                ('security_considerations', models.TextField()),
                ('conclusion', models.TextField()),
                ('approver_name', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
            ],
            options={
                'db_table': 'API_FirmwareLowLevelDesign',
            },
        ),
    ]
