# Generated by Django 5.1.4 on 2025-03-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_firmwarelowleveldesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareProtocolDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('firmware_version', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('scope', models.TextField()),
                ('references', models.TextField()),
                ('supported_protocols', models.TextField()),
                ('data_transmission_modes', models.TextField()),
                ('uart_protocol', models.TextField()),
                ('spi_protocol', models.TextField()),
                ('i2c_protocol', models.TextField()),
                ('can_protocol', models.TextField()),
                ('message_structure', models.TextField()),
                ('error_handling', models.TextField()),
                ('security_considerations', models.TextField()),
                ('conclusion', models.TextField()),
                ('approver_name', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
            ],
            options={
                'db_table': 'API_Firmware Protocol Document',
            },
        ),
    ]
