# Generated by Django 5.1.4 on 2025-03-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_firmwareprotocoldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='RS485ModbusProtocolDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('firmware_version', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('prepared_by', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('scope', models.TextField()),
                ('references', models.TextField()),
                ('protocol_type', models.TextField()),
                ('transmission_mode', models.TextField()),
                ('data_transmission_modes', models.TextField()),
                ('rs485_physical_layer', models.TextField()),
                ('modbus_rtu_frame_format', models.TextField()),
                ('modbus_ascii_frame_format', models.TextField()),
                ('function_codes', models.TextField()),
                ('error_handling', models.TextField()),
                ('security_considerations', models.TextField()),
                ('conclusion', models.TextField()),
                ('approver_name', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
            ],
            options={
                'db_table': 'API_RS485 Modbus Protocol Document',
            },
        ),
    ]
