# Generated by Django 5.1.4 on 2025-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rs485modbusprotocoldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighLevelDesignDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('prepared_by', models.CharField(max_length=255)),
                ('reviewed_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('references', models.TextField()),
                ('system_description', models.TextField()),
                ('block_diagram', models.TextField()),
                ('key_functionalities', models.TextField()),
                ('functional_requirements', models.TextField()),
                ('performance_requirements', models.TextField()),
                ('hardware_requirements', models.TextField()),
                ('software_requirements', models.TextField()),
                ('environmental_requirements', models.TextField()),
                ('regulatory_compliance', models.TextField()),
                ('safety_protection', models.TextField()),
                ('design_constraints', models.TextField()),
                ('assumptions', models.TextField()),
                ('risk_analysis', models.TextField()),
                ('version_date', models.DateField()),
                ('author_changes', models.TextField()),
            ],
            options={
                'db_table': 'API _ High-Level Design Document details',
            },
        ),
    ]
