# Generated by Django 5.1.4 on 2025-03-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_highleveldesigndocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareHLDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('definitions_acronyms_abbreviations', models.TextField()),
                ('references', models.TextField()),
                ('system_purpose_objectives', models.TextField()),
                ('high_level_architecture', models.TextField()),
                ('system_context', models.TextField()),
                ('architectural_style', models.TextField()),
                ('component_design', models.TextField()),
                ('data_flow', models.TextField()),
                ('communication_integration', models.TextField()),
                ('user_interface_overview', models.TextField()),
                ('interaction_design', models.TextField()),
                ('database_overview', models.TextField()),
                ('data_flow_processing', models.TextField()),
                ('data_security', models.TextField()),
                ('performance', models.TextField()),
                ('security', models.TextField()),
                ('availability_reliability', models.TextField()),
                ('scalability', models.TextField()),
                ('maintainability', models.TextField()),
                ('user_interfaces', models.TextField()),
                ('hardware_interfaces', models.TextField()),
                ('software_interfaces', models.TextField()),
                ('deployment_architecture', models.TextField()),
                ('hardware_network_requirements', models.TextField()),
                ('glossary', models.TextField()),
                ('diagrams', models.TextField()),
            ],
            options={
                'db_table': 'API_softwarehlddocument',
            },
        ),
        migrations.AlterModelTable(
            name='highleveldesigndocument',
            table='API_High-Level Design Document details',
        ),
    ]
