# Generated by Django 5.1.4 on 2025-03-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_softwarehlddocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareLLDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('definitions_acronyms_abbreviations', models.TextField()),
                ('references', models.TextField()),
                ('architectural_design', models.TextField()),
                ('design_constraints', models.TextField()),
                ('assumptions_dependencies', models.TextField()),
                ('module_purpose', models.TextField()),
                ('module_interfaces', models.TextField()),
                ('component_design', models.TextField()),
                ('data_flow', models.TextField()),
                ('error_handling', models.TextField()),
                ('performance_considerations', models.TextField()),
                ('security_considerations', models.TextField()),
                ('unit_tests', models.TextField()),
                ('database_overview', models.TextField()),
                ('database_schema', models.TextField()),
                ('data_access_layer_design', models.TextField()),
                ('internal_communication', models.TextField()),
                ('external_communication', models.TextField()),
                ('integration_external_systems', models.TextField()),
                ('integration_other_modules', models.TextField()),
                ('user_interface_components', models.TextField()),
                ('ui_logic', models.TextField()),
                ('unit_testing_strategy', models.TextField()),
                ('integration_testing', models.TextField()),
                ('performance_testing', models.TextField()),
                ('code_reviews_static_analysis', models.TextField()),
                ('appendix', models.TextField()),
            ],
            options={
                'db_table': 'API_SoftwareLLDDocument',
            },
        ),
    ]
