# Generated by Django 5.1.4 on 2025-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_softwarellddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareSRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('prepared_by', models.CharField(max_length=255)),
                ('reviewed_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('definitions_acronyms_abbreviations', models.TextField()),
                ('references', models.TextField()),
                ('overview', models.TextField()),
                ('product_perspective', models.TextField()),
                ('user_classes_characteristics', models.TextField()),
                ('operating_environment', models.TextField()),
                ('design_implementation_constraints', models.TextField()),
                ('assumptions_dependencies', models.TextField()),
                ('hardware_design', models.TextField()),
                ('user_interfaces', models.TextField()),
                ('hardware_interfaces', models.TextField()),
                ('software_interfaces', models.TextField()),
                ('communication_interfaces', models.TextField()),
                ('reliability', models.TextField()),
                ('availability', models.TextField()),
                ('security', models.TextField()),
                ('maintainability', models.TextField()),
                ('portability', models.TextField()),
                ('performance', models.TextField()),
                ('scalability', models.TextField()),
                ('usability', models.TextField()),
                ('legal_regulatory', models.TextField()),
                ('appendix', models.TextField()),
            ],
            options={
                'db_table': 'API_Software Requirements Specification (SRS) Document',
            },
        ),
    ]
