# Generated by Django 5.1.4 on 2025-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_softwaresrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareTestSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('test_objectives', models.TextField()),
                ('definitions_acronyms_abbreviations', models.TextField()),
                ('references', models.TextField()),
                ('test_levels', models.TextField()),
                ('test_types', models.TextField()),
                ('test_approach', models.TextField()),
                ('test_environment', models.TextField()),
                ('features_to_be_tested', models.TextField()),
                ('features_not_to_be_tested', models.TextField()),
                ('entry_criteria', models.TextField()),
                ('exit_criteria', models.TextField()),
                ('test_cases', models.TextField()),
                ('test_execution_schedule', models.TextField()),
                ('resource_requirements', models.TextField()),
                ('defect_reporting', models.TextField()),
                ('defect_lifecycle', models.TextField()),
                ('severity_priority', models.TextField()),
                ('risks', models.TextField()),
                ('mitigation_strategies', models.TextField()),
                ('test_reports', models.TextField()),
                ('test_logs', models.TextField()),
                ('test_artifacts', models.TextField()),
                ('appendix', models.TextField()),
            ],
        ),
    ]
