# Generated by Django 5.1.4 on 2025-03-05 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_softwaretestspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareLLD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('prepared_by', models.CharField(max_length=255)),
                ('reviewed_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('references', models.TextField()),
                ('block_diagram', models.TextField()),
                ('test_equipment_used', models.TextField()),
                ('operating_conditions', models.TextField()),
                ('conclusion', models.TextField()),
                ('suggested_fixes', models.TextField()),
                ('additional_tests', models.TextField()),
                ('approval_status', models.TextField()),
                ('approver_name', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
            ],
            options={
                'db_table': 'API_HardwareLLD',
            },
        ),
        migrations.CreateModel(
            name='IssueObservationLLD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('hardware_lld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='myapp.hardwarelld')),
            ],
            options={
                'db_table': 'API_HardwareLLD_IssueObservation',
            },
        ),
        migrations.CreateModel(
            name='TestCaseLLD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_no', models.IntegerField()),
                ('test_description', models.TextField()),
                ('expected_outcome', models.TextField()),
                ('actual_outcome', models.TextField()),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('hardware_lld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='myapp.hardwarelld')),
            ],
            options={
                'db_table': 'API_HardwareLLD_TestCase',
            },
        ),
    ]
