# Generated by Django 5.1.4 on 2025-03-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_hardwarelld_issueobservationlld_testcaselld'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowLevelDesignFunctional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('prepared_by', models.CharField(max_length=255)),
                ('reviewed_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('references', models.TextField()),
                ('overview', models.TextField()),
                ('module_specifications', models.TextField()),
                ('microcontroller_processor', models.TextField()),
                ('memory_map', models.TextField()),
                ('peripheral_interfaces', models.TextField()),
                ('power_management', models.TextField()),
                ('firmware_architecture', models.TextField()),
                ('task_scheduling', models.TextField()),
                ('interrupt_handling', models.TextField()),
                ('data_structures_algorithms', models.TextField()),
                ('error_handling_debugging', models.TextField()),
                ('internal_communication', models.TextField()),
                ('external_communication', models.TextField()),
                ('security_features', models.TextField()),
                ('safety_mechanisms', models.TextField()),
                ('timing_constraints', models.TextField()),
                ('resource_utilization', models.TextField()),
                ('unit_testing', models.TextField()),
                ('integration_testing', models.TextField()),
                ('validation_criteria', models.TextField()),
                ('version_date', models.DateField()),
                ('author_changes', models.TextField()),
            ],
            options={
                'db_table': 'API_LowLevelDesign_Functional',
            },
        ),
        migrations.CreateModel(
            name='TestCaseFunctionalLLD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_no', models.IntegerField()),
                ('test_description', models.TextField()),
                ('expected_outcome', models.TextField()),
                ('actual_outcome', models.TextField()),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('lld_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='myapp.lowleveldesignfunctional')),
            ],
            options={
                'db_table': 'API_LLD_Functional_TestCase',
            },
        ),
    ]
