# Generated by Django 5.1.4 on 2025-03-06 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_lowleveldesignfunctional_testcasefunctionallld'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('prepared_by', models.CharField(max_length=255)),
                ('reviewed_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('dependencies_risks', models.TextField()),
                ('version_date', models.DateField()),
                ('author_changes', models.TextField()),
            ],
            options={
                'db_table': 'API_MilestoneSchedule',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('milestone_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='myapp.milestoneschedule')),
            ],
            options={
                'db_table': 'API_Milestone',
            },
        ),
    ]
