# Generated by Django 5.1.4 on 2025-03-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_milestoneschedule_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UATDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('prepared_by', models.CharField(max_length=255)),
                ('reviewed_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('references', models.TextField()),
                ('overview', models.TextField()),
                ('assumptions', models.TextField()),
                ('test_environment', models.TextField()),
                ('hardware_design', models.TextField()),
                ('defect_logging', models.TextField()),
                ('resolution_process', models.TextField()),
                ('test_results_summary', models.TextField()),
                ('acceptance_decision', models.TextField()),
                ('version_date', models.DateField()),
                ('author_changes', models.TextField()),
            ],
            options={
                'db_table': 'API_UAT_Document',
            },
        ),
        migrations.CreateModel(
            name='UATTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('expected_results', models.TextField()),
                ('actual_results', models.TextField()),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('uat_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='myapp.uatdocument')),
            ],
            options={
                'db_table': 'API_UAT_Test_Cases',
            },
        ),
    ]
